sudo: required
language: python
dist: xenial
cache: pip
python:
- '3.6'
- '3.7'
install:
- pip install --upgrade pip
- pip install --progress-bar off .[tensorflow-cpu]
- pip install flake8==3.7.7
- pip install pytest
jobs:
  include:
  - stage: docs
    python: '3.7'
    install:
    - pip install --upgrade pip
    - pip install --progress-bar off -r requirements.txt
    - pip install --progress-bar off -r docs/requirements.txt
    script:
    - cd docs
    - sphinx-build -b html -d _build/doctrees . _build/html
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
